### ISSUE TITLE
Chapter 4, Page 49 missing or non-existent phpstorm option mentioned

### ISSUE THREAD

**Issue by bonrita** [bitpressio/docker-for-php-developers-errata#10] opened 2018-08-31 09:37 UTC
On the following screen, click the plus (+) button in the top left and select "PHP Web Application" to create a run configuration.

**Comment by bonrita** [comment] 2018-08-31 09:38
The option "PHP Web Application" does not exist in phpstorm at least in version 2018.2

**Comment by paulredmond** [comment] 2018-09-01 00:00
Thanks for reporting @bonrita.

They've updated the menus in the latest version of PHPStorm, which is unfortunate, the correct selection is **PHP Remote Debug**

**Comment by paulredmond** [comment] 2018-09-01 00:07
I am going to keep this open until I've updated and published a new version of the book. The errata has been updated with this info, thank you.

https://github.com/bitpressio/docker-for-php-developers-errata/blob/master/errata.md#-missing-option-in-phpstorm-2018

**Comment by paulredmond** [comment] 2018-09-01 00:08
As I am allowing errata to flow in for a while, please check back to the errata document and the issues here. It's easier for me to allow time for reports before publishing a new edition, but I'll make sure to keep the errata as up-to-date as possible, so feel free to open any issues you come across!

**Comment by paulredmond** [comment] 2018-09-04 17:02
Duplicate of #7, you can follow along with that issue to find out when its published in an updated future version of the text.

**Closed by paulredmond** 2018-09-04 17:02 UTC
Labels: manuscript updated, needs pdf changes
